theme: jekyll-theme-minimal
title: ".NET Foundation Elections"
description: "This is your .NET Foundation! Get involved by voting for - or possibly running for - our next Board of Directors."

collections:
  campaign-2019:
    output: true

# Google Analytics
google_analytics: UA-57261022-1

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
